services:             
    cosc304-mysql:
        image: mysql:8.4
        container_name: cosc304-mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'testuser'
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: '304testpw'            
            MYSQL_ROOT_PASSWORD: '304rootpw'
        ports:
            - '3306:3306'
        expose:
            - '3306'   
        volumes:
            - mysql-db:/var/lib/mysql
            - ./ddl:/docker-entrypoint-initdb.d
    cosc304-sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: cosc304-sqlserver
        restart: always
        environment:
            ACCEPT_EULA: 'Y'
            MSSQL_SA_PASSWORD: '304#sa#pw'                  
        ports:
            - '1433:1433'
        expose:
            - '1433'
        volumes:
            - cosc304-db:/var/lib/mssql            
            - ./ddl:/scripts
        command:                                            
            - /bin/bash
            - -c
            - |
               /opt/mssql/bin/sqlservr &
               pid=$$!
               echo "Waiting for MS SQL to be available"
               /opt/mssql-tools18/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$MSSQL_SA_PASSWORD -No -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername"
               is_up=$$? 
               while [ $$is_up -ne 0 ] ; do 
                 echo -e $$(date) 
                 /opt/mssql-tools18/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$MSSQL_SA_PASSWORD -No -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername" 
                 is_up=$$?
                 sleep 5 
               done
               for foo in /scripts/SQLServer*.ddl
                 do /opt/mssql-tools18/bin/sqlcmd -U sa -P $$MSSQL_SA_PASSWORD -No -l 30 -e -i $$foo 
               done
               trap "kill -15 $$pid" SIGTERM
               wait $$pid
               exit 0
volumes: 
    cosc304-db:
    mysql-db:
